# Generated by Django 2.2 on 2019-04-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190419_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='hello-world-default-slug'),
            preserve_default=False,
        ),
    ]
